/**
 * content-brief.ts — Stage A planning: which pieces a period yields, and the
 * brief for each (rules §2-§4, §8a).
 *
 *   planPieces()  one OpenRouter call over the period's library page →
 *                 ≤1 highlight + ≤3 how-to candidates, each with a subtopic,
 *                 1-2 search queries and the row range it is built from.
 *   buildBriefs() one call over the candidates + their research digests →
 *                 per piece: VIEWER (from research), situation, tier, format
 *                 (from the catalog), the research problems it speaks to.
 * Deterministic validation after each call: unknown tiers/formats, rows outside
 * the period, or a missing viewer fall back to safe defaults rather than failing.
 * Throws CapError (cap) or Error (model) — content-run records either.
 */

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { llmJson, type ContentLlmOptions } from './content-llm.js'
import { BRIEF_RULES, FORMAT_CATALOG, TIER_TEMPLATES, type Tier } from './content-script-rules.js'
import type { TopicResearch } from './content-research.js'
import { researchDigest } from './content-research.js'

export const OWNER_FILE = 'content-owner.json'
const PAGE_MAX_CHARS = 60_000

export interface PieceCandidate {
  id: string
  kind: Tier
  subtopic: string
  story: string
  queries: string[]
  fromRow: number
  toRow: number
  why: string
}

export interface Owner {
  name: string
  handle?: string
}

export interface Stake {
  /** What is measured, e.g. "facts recalled after compaction". */
  quantity: string
  before: string
  after: string
}

export interface Brief {
  id: string
  tier: Tier
  subtopic: string
  story: string
  fromRow: number
  toRow: number
  /** WHO is consuming it (rules §4), picked from the research. */
  viewer: string
  /** What that viewer is living through. */
  situation: string
  /** Format id from FORMAT_CATALOG. */
  format: string
  angle: string
  /** Research problems (§8a) the piece speaks to. */
  problems: string[]
  /** WHAT-WORKS rule 1: the before -> after quantity or verdict the piece shows. Null = no provable stake (not scripted). */
  stake: Stake | null
  researchKey: string
  owner: Owner | null
  autoGenerated: true
}

const str = (v: unknown, n = 300) => String(v ?? '').replace(/\s+/g, ' ').trim().slice(0, n)

/** Developer who owns the pieces (rules §6): env first, then <project>/content-owner.json. Null when unknown. */
export function loadOwner(projectDir: string | null): Owner | null {
  const name = str(process.env.OSBORN_CONTENT_OWNER_NAME, 80)
  if (name) return { name, handle: str(process.env.OSBORN_CONTENT_OWNER_HANDLE, 80) || undefined }
  if (!projectDir) return null
  try {
    const p = join(projectDir, OWNER_FILE)
    if (!existsSync(p)) return null
    const o = JSON.parse(readFileSync(p, 'utf-8'))
    const n = str(o?.name, 80)
    return n ? { name: n, handle: str(o?.handle ?? o?.github, 80) || undefined } : null
  } catch {
    return null
  }
}

export const PLAN_SYSTEM =
  'You plan short developer videos from ONE period of a developer\'s work session with an AI coding agent. ' +
  'You only use what the period page shows. Reply with ONE JSON object only.'

export function planPrompt(page: string, maxHighlights: number, maxHowtos: number, range: { from: number; to: number }): string {
  return [
    'Below is the library page for one work period (goal, ranked work, arc, stories, quotes with row numbers).',
    '<period_page>',
    page.length > PAGE_MAX_CHARS ? page.slice(0, PAGE_MAX_CHARS) : page,
    '</period_page>',
    `TASK: pick at most ${maxHighlights} highlight and at most ${maxHowtos} how-to piece(s).`,
    `- highlight = ${TIER_TEMPLATES.highlight.promise} Pick the period's strongest arc.`,
    `- howto = ${TIER_TEMPLATES.howto.promise} Only for something concrete someone else could copy. Skip if the period has none.`,
    'Each piece: {"id": "p1"..., "kind": "highlight"|"howto", "subtopic": the problem space in 3-8 words a stranger would search, ' +
      '"story": the story title from the page it is built on, "queries": 1-2 SHORT searches (2-4 words) for the underlying general problem, phrased the way outsiders search HN / GitHub issues ' +
      '(e.g. "claude code compaction", "api key machine auth"); no project-specific names or phrases, ' +
      `"from_row", "to_row": the row range on the page it comes from (within ${range.from}-${range.to}), "why": one line}.`,
    'Never plan pieces about invoices, payments owed, contracts or rates. Keep [client]-style tags; never guess names.',
    'Output ONLY: {"pieces": [...]}',
  ].join('\n\n')
}

export function validateCandidates(raw: unknown, range: { from: number; to: number }, maxPieces: number): PieceCandidate[] {
  const list: any[] = Array.isArray((raw as any)?.pieces) ? (raw as any).pieces : Array.isArray(raw) ? (raw as any[]) : []
  const out: PieceCandidate[] = []
  let highlights = 0
  let howtos = 0
  for (const p of list) {
    const k = str(p?.kind ?? p?.tier, 20).toLowerCase().replace(/[^a-z]/g, '')
    const kind: Tier | null = k.startsWith('highlight') ? 'highlight' : k.startsWith('howto') ? 'howto' : null
    const subtopic = str(p?.subtopic ?? p?.topic ?? p?.title ?? p?.story, 120)
    if (!kind || !subtopic) continue
    if (kind === 'highlight' ? highlights >= 1 : howtos >= 3) continue
    if (out.length >= maxPieces) break
    const a = Math.floor(Number(p?.from_row ?? p?.fromRow))
    const b = Math.floor(Number(p?.to_row ?? p?.toRow))
    const fromRow = Number.isFinite(a) && a >= range.from && a <= range.to ? a : range.from
    const toRow = Number.isFinite(b) && b >= fromRow && b <= range.to ? b : range.to
    const queries = (Array.isArray(p?.queries) ? p.queries : [])
      .map((q: unknown) => str(q, 60))
      .filter((q: string) => q.split(' ').length >= 2)
      .slice(0, 2)
    if (kind === 'highlight') highlights++
    else howtos++
    out.push({ id: `${kind}-${kind === 'highlight' ? highlights : howtos}`, kind, subtopic, story: str(p?.story, 160), queries: queries.length ? queries : [subtopic.split(' ').slice(0, 5).join(' ')], fromRow, toRow, why: str(p?.why, 200) })
  }
  // Highlight first, then how-tos (stable ids → stable content hashes across reruns).
  return out.sort((x, y) => (x.kind === y.kind ? 0 : x.kind === 'highlight' ? -1 : 1))
}

/** Plan this period's pieces. One model call. */
export async function planPieces(page: string, range: { from: number; to: number }, maxPieces: number, llm: ContentLlmOptions): Promise<{ candidates: PieceCandidate[]; costUsd: number }> {
  if (maxPieces <= 0) return { candidates: [], costUsd: 0 }
  const maxHow = Math.min(3, Math.max(0, maxPieces - 1))
  const r = await llmJson(llm, { what: 'plan', system: PLAN_SYSTEM, user: planPrompt(page, 1, maxHow, range), maxOut: 1500, temperature: 0.2 })
  return { candidates: validateCandidates(r.json, range, maxPieces), costUsd: r.costUsd }
}

export const BRIEF_SYSTEM =
  'You write video briefs for a developer\'s own short videos. Every brief starts with WHO is watching and what they are living through, ' +
  'taken from the research given (never invented). Reply with ONE JSON object only.'

export function catalogText(tier: Tier): string {
  return FORMAT_CATALOG.filter(f => f.tiers.includes(tier))
    .map(f => `- ${f.id}: ${f.name}. Needs: ${f.needs}. Beats: ${f.beats}. Use when: ${f.whenToUse}. Evidence: ${f.evidence}.`)
    .join('\n')
}

export function briefPrompt(cands: PieceCandidate[], research: Map<string, TopicResearch>): string {
  const blocks = cands.map(c => {
    const r = research.get(c.id)
    return [
      `PIECE ${c.id} (${TIER_TEMPLATES[c.kind].label})`,
      `Subtopic: ${c.subtopic}. Built on: "${c.story}" (rows ${c.fromRow}-${c.toRow}). Why: ${c.why}`,
      r ? researchDigest(r) : 'RESEARCH: none available',
      `FORMATS that fit this tier:\n${catalogText(c.kind)}`,
    ].join('\n')
  })
  return [
    ...blocks,
    `RULES:\n${BRIEF_RULES.map(r => `- ${r}`).join('\n')}`,
    'For EACH piece return {"id", "viewer": who is consuming it (role + situation, from the research), "situation": what they are living through (1 line), ' +
      '"format": one format id from its list, "angle": the one-line promise of the piece to that viewer, ' +
      '"problems": 1-3 of the research problems/scenarios it speaks to (copy their text), ' +
      '"stake": {"quantity": what is measured, "before": the value/verdict before, "after": the same quantity after} taken from the session, or null if the session shows no provable before/after}.',
    'Output ONLY: {"briefs": [...]}',
  ].join('\n\n')
}

/** A stake needs all three parts, and before must differ from after. */
export function validStake(v: unknown): Stake | null {
  const o: any = v && typeof v === 'object' ? v : null
  if (!o) return null
  const quantity = str(o.quantity ?? o.what, 160)
  const before = str(o.before, 120)
  const after = str(o.after, 120)
  if (!quantity || !before || !after || before.toLowerCase() === after.toLowerCase()) return null
  return { quantity, before, after }
}

const DEFAULT_FORMAT: Record<Tier, string> = { highlight: 'narrated-timeline', howto: 'two-voice-hud' }

export function validateBriefs(raw: unknown, cands: PieceCandidate[], research: Map<string, TopicResearch>, owner: Owner | null): Brief[] {
  const list: any[] = Array.isArray((raw as any)?.briefs) ? (raw as any).briefs : []
  const byId = new Map(list.map(b => [str(b?.id, 40), b]))
  return cands.map((c, i) => {
    const b = byId.get(c.id) ?? list[i] ?? {}
    const r = research.get(c.id)
    const fmt = str(b?.format, 40).toLowerCase()
    const format = FORMAT_CATALOG.some(f => f.id === fmt && f.tiers.includes(c.kind)) ? fmt : DEFAULT_FORMAT[c.kind]
    const viewer = str(b?.viewer ?? b?.audience, 200) || r?.viewers[0]?.text || `developers working on ${c.subtopic}`
    const problems = (Array.isArray(b?.problems) ? b.problems : []).map((p: unknown) => str(p, 240)).filter(Boolean).slice(0, 3)
    return {
      id: c.id, tier: c.kind, subtopic: c.subtopic, story: c.story, fromRow: c.fromRow, toRow: c.toRow,
      viewer, situation: str(b?.situation, 240) || (r?.problems[0]?.text ?? c.subtopic), format, angle: str(b?.angle, 240) || c.why,
      problems: problems.length ? problems : (r?.problems ?? []).slice(0, 2).map(p => p.text),
      stake: validStake(b?.stake), researchKey: r?.key ?? '', owner, autoGenerated: true,
    }
  })
}

/** Build all briefs for a period in one model call. */
export async function buildBriefs(cands: PieceCandidate[], research: Map<string, TopicResearch>, owner: Owner | null, llm: ContentLlmOptions): Promise<{ briefs: Brief[]; costUsd: number }> {
  if (!cands.length) return { briefs: [], costUsd: 0 }
  const r = await llmJson(llm, { what: 'brief', system: BRIEF_SYSTEM, user: briefPrompt(cands, research), maxOut: 1500, temperature: 0.2 })
  return { briefs: validateBriefs(r.json, cands, research, owner), costUsd: r.costUsd }
}
